### ISSUE TITLE
Why is ":" separated in the string?

### ISSUE THREAD

**Issue by shah** [shah/ccf-container-defns#1]
@sijomc please see:

https://github.com/shah/ccf-container-defns/blob/b2c25297af197f14dc55fd9ac4f6ad51d4aec97e/tt-rss-container.ccf-defn.jsonnet#L13

I'm wondering why is this written this way:

    'linuxserver/tt-rss'+':142'

rather than:

    'linuxserver/tt-rss:142'

**Comment by sijomc** [comment]
@shah corrected these line

**Comment by sijomc** [comment]
@shah corrected these line
