### ISSUE TITLE
Put the config file in as part of the container build

### ISSUE THREAD

**Issue by shah** [shah/ccf-container-defns#2]
Sijo, I'm wodering why you have not used volumes or did not just put this file into the build itself?

https://github.com/shah/ccf-container-defns/blob/b2c25297af197f14dc55fd9ac4f6ad51d4aec97e/tt-rss-container.ccf-defn.jsonnet#L56

It's not a good idea to change the container after it's built.

**Comment by sijomc** [comment]
@shah Volume has enabled in tt-rss container. Here I am just copying initial configurations, which is also mounted in volume.

**Comment by shah** [comment]
@sijomc if this available in a volume, then there's no need for the separate copy. Please make sure you never touch a container after it's been created (must stay immutable).
