### ISSUE TITLE
Replace custom script with ccfLib.bashSnippets.waitForContainerLogMessage

### ISSUE THREAD

**Issue by shah** [shah/ccf-container-defns#3]
@sijomc please replace this:

https://github.com/shah/ccf-container-defns/blob/86816b47c92df9292e9d1b3deb50761a350ff7c7/tt-rss-container.ccf-defn.jsonnet#L43

"after_start.make-plugin.sh" : ccfLib.bashSnippets.waitForContainerLogMessage(context, ""starting services")

Since you do not need the special docker cp line, you can replace the entire block.

There's an example of how it's used in the ms-sqlserver CCF container definition.

**Comment by sijomc** [comment]
@shah Updated.

**Comment by shah** [comment]
@sijomc this is not correct -- it looks like you changed the code but did not test it?

Please be sure not use ||| otherwise you're creating a quoted string, not jsonnet code. 
Use:

	"after_start.make-plugin.sh" :
		ccflib.bashSnippets.preamble(context) + 
		ccflib.bashSnippets.waitForContainerLogMessage(context, 'SQL Server is now ready for client connections.'),

**NOT**:

	"after_start.make-plugin.sh" : |||
		ccflib.bashSnippets.preamble(context) + 
		ccflib.bashSnippets.waitForContainerLogMessage(context, 'SQL Server is now ready for client connections.'),
                |||

**Comment by sijomc** [comment]
@shah Corrected these lines and ensured the working of container definition.
