### ISSUE TITLE
Use variables for ports

### ISSUE THREAD

**Issue by shah** [shah/ccf-container-defns#5]
@sijomc Remove hard coding: 

https://github.com/shah/ccf-container-defns/blob/d79cc7d88b7571fe8cb18cdd65d11c403b0a45e3/hugo.ccf-defn.jsonnet#L109

https://github.com/shah/ccf-container-defns/blob/d79cc7d88b7571fe8cb18cdd65d11c403b0a45e3/hugo.ccf-defn.jsonnet#L50

**Comment by sijomc** [comment]
@shah Removed hardcoding and updated container definition
